### ISSUE TITLE
辣鸡

### ISSUE THREAD

**Issue by 18703876065** [coderliguoqing/distributed-seckill#3]
搞个图就尼玛瞎比比

**Comment by coderliguoqing** [comment]
看了一眼你的历史评价，让我想起了詹姆斯与贝弗利的故事，一条疯狗追着詹姆斯咬，但这仅仅是你作为一条疯狗表现出来的素质而已，你咬的人并不会有什么波澜！

**Comment by coderliguoqing** [comment]
@18703876065 看了一眼你的历史评价，让我想起了詹姆斯与贝弗利的故事，一条疯狗追着詹姆斯咬，但这仅仅是你作为一条疯狗表现出来的素质而已，你咬的人并不会有什么波澜！
